# Makefile for the a2 project

# --- Compiler Configuration ---
CC = gcc
# Simplified CFLAGS for the a2 project
CFLAGS = -g -Wall -Wextra -I. -I./a2_files $(shell pkg-config --cflags hunspell)
LDFLAGS = -lncursesw -ljansson -lcurl -lpthread -ldl -lssl -lcrypto -lvterm $(shell pkg-config --libs hunspell) -lm -Wl,-rpath=/usr/local/lib

# --- Main Target ---
TARGET = a2

# --- Directories ---
A2_DIR = a2_files

# The default 'all' target builds the executable
all: $(TARGET)


# --- Compilation Rules for the 'a2' Editor ---

# Source files for a2
A2_SOURCES = a2.c command_execution.c defs.c direct_navigation.c fileio.c lsp_client.c others.c screen_ui.c window_managment.c project.c timer.c cache.c explorer.c diff.c themes.c spell.c settings.c
# Adds the directory prefix to source and object files
A2_SRCS = $(addprefix $(A2_DIR)/, $(A2_SOURCES))
A2_OBJS = $(A2_SRCS:.c=.o)

# Rule to link the a2 executable (in the project root)
$(TARGET): $(A2_OBJS)
	$(CC) $(CFLAGS) -o $@ $(A2_OBJS) $(LDFLAGS)

# Pattern rule to compile a2 .c files into .o
$(A2_DIR)/%.o: $(A2_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@


# --- Assembly Directory ---
ASM_DIR = asm

# Assembly files for a2
A2_ASMS = $(patsubst $(A2_DIR)/%.c,$(ASM_DIR)/%.s,$(A2_SRCS))

# Target to generate assembly code
assem: $(ASM_DIR) $(A2_ASMS)
	@echo "Assembly files generated in $(ASM_DIR)/"

# Creates the assembly directory if it doesn't exist
$(ASM_DIR):
	mkdir -p $(ASM_DIR)

# Rule to compile .c files into .s (assembly)
$(ASM_DIR)/%.s: $(A2_DIR)/%.c
	$(CC) $(CFLAGS) -S $< -o $@


# --- Clean and Utility Targets ---

# Cleans all files generated by this Makefile
clean:
	rm -f $(TARGET) $(A2_OBJS)
	rm -rf $(ASM_DIR)

# Generates compile_commands.json
compile_commands:
	@echo "To generate compile_commands.json for the a2 editor, run: bear -- make"

# Target to install the executable on the system
install: all
	@echo "Installing a2 executable in /usr/local/bin..."
	-sudo rm -f /usr/local/bin/$(TARGET)
	sudo cp $(TARGET) /usr/local/bin/$(TARGET)
	@echo "Installing syntaxes and themes..."
	sudo mkdir -p /usr/local/share/a2/syntaxes
	sudo cp -r syntaxes/* /usr/local/share/a2/syntaxes/
	@echo "Installing help files..."
	sudo mkdir -p /usr/local/share/a2/man
	sudo cp -r man/*.txt /usr/local/share/a2/man/
	@echo "Installation complete."
    
# Target to force clean, compile, and install in a single command
rebuild: clean install

.PHONY: all clean compile_commands install rebuild assem
